const softSkills = [
  "Problem Solving",
  "Critical Thinking",
  "Communication",
  "Team Collaboration",
  "Time Management",
  "Adaptability",
  "Creativity",
  "Attention to Detail",
  "Self-Motivation",
  "Responsibility",
  "Conflict Resolution",
  "Emotional Intelligence",
  "Active Listening",
  "Decision Making",
  "Analytical Thinking",
  "Leadership",
  "Stress Management",
  "Work Ethic",
  "Openness to Feedback",
  "Continuous Learning",
  "Organization",
  "Task Prioritization",
  "Accountability",
  "Patience",
  "Empathy",
  "Negotiation",
  "Presentation Skills",
  "Remote Work Discipline",
  "Initiative",
  "Goal Setting",
  "Flexibility",
  "Collaboration Across Teams",
  "Problem Ownership",
  "Clear Documentation",
  "Mentorship",
  "Curiosity",
  "Reliability",
  "Strategic Thinking",
  "User-Centered Thinking",
];

const languages = [
  "English",
  "Georgian",
  "Russian",
  "German",
  "French",
  "Spanish",
  "Italian",
  "Portuguese",
  "Dutch",
  "Polish",
  "Ukrainian",
  "Turkish",
  "Arabic",
  "Chinese (Mandarin)",
  "Japanese",
  "Korean",
  "Hindi",
  "Bengali",
  "Urdu",
  "Persian",
  "Hebrew",
  "Greek",
  "Swedish",
  "Norwegian",
  "Finnish",
  "Danish",
  "Czech",
  "Slovak",
  "Hungarian",
  "Romanian",
];

const technicalSkills = [
  "HTML5",
  "CSS3",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Express.js",
  "NestJS",
  "MongoDB",
  "PostgreSQL",
  "Prisma",
  "Mongoose",
  "REST APIs",
  "GraphQL",
  "Redux",
  "Redux Toolkit",
  "Zustand",
  "Tailwind CSS",
  "Sass",
  "Bootstrap",
  "Framer Motion",
  "React Hook Form",
  "Zod",
  "JWT Authentication",
  "NextAuth",
  "Socket.IO",
  "WebSockets",
  "Git",
  "GitHub",
  "Docker",
  "CI/CD",
  "Vercel",
  "Linux Basics",
  "Nginx",
  "MVC Architecture",
  "Clean Architecture",
  "Server Actions",
  "API Security",
  "Unit Testing",
  "Jest",
  "Playwright",
  "Postman",
  "Swagger",
  "Performance Optimization",
  "SEO Basics",
  "Responsive Design",
  "Accessibility (a11y)",
  "System Design Basics",
];

export const skillsData = {
  soft: softSkills,
  languages: languages,
  technical: technicalSkills,
};
